// =============================================================================
// Enums — synced with Prisma schema (source of truth)
// =============================================================================

export enum UserRole {
  PATIENT = 'PATIENT',
  NURSE = 'NURSE',
  CLINICAL_OFFICER = 'CLINICAL_OFFICER',
  DOCTOR = 'DOCTOR',
  PHYSIOTHERAPIST = 'PHYSIOTHERAPIST',
  PHARMACIST = 'PHARMACIST',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum PractitionerType {
  REGISTERED_NURSE = 'REGISTERED_NURSE',
  ENROLLED_NURSE = 'ENROLLED_NURSE',
  CLINICAL_OFFICER = 'CLINICAL_OFFICER',
  GENERAL_PRACTITIONER = 'GENERAL_PRACTITIONER',
  SPECIALIST_DOCTOR = 'SPECIALIST_DOCTOR',
  PHYSIOTHERAPIST = 'PHYSIOTHERAPIST',
  PHARMACIST = 'PHARMACIST',
  MIDWIFE = 'MIDWIFE',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PRACTITIONER_EN_ROUTE = 'PRACTITIONER_EN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  DISPUTED = 'DISPUTED',
}

export enum ServiceType {
  GENERAL_CONSULTATION = 'GENERAL_CONSULTATION',
  NURSING_CARE = 'NURSING_CARE',
  WOUND_DRESSING = 'WOUND_DRESSING',
  INJECTION_ADMINISTRATION = 'INJECTION_ADMINISTRATION',
  IV_THERAPY = 'IV_THERAPY',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY',
  MATERNAL_CARE = 'MATERNAL_CARE',
  CHILD_WELLNESS = 'CHILD_WELLNESS',
  CHRONIC_DISEASE_MANAGEMENT = 'CHRONIC_DISEASE_MANAGEMENT',
  PALLIATIVE_CARE = 'PALLIATIVE_CARE',
  POST_OPERATIVE_CARE = 'POST_OPERATIVE_CARE',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  PHARMACY_DELIVERY = 'PHARMACY_DELIVERY',
  LAB_SAMPLE_COLLECTION = 'LAB_SAMPLE_COLLECTION',
  EMERGENCY_TRIAGE = 'EMERGENCY_TRIAGE',
  VIRTUAL_CONSULTATION = 'VIRTUAL_CONSULTATION',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  DISPUTED = 'DISPUTED',
}

export enum PaymentMethod {
  MOBILE_MONEY_MTN = 'MOBILE_MONEY_MTN',
  MOBILE_MONEY_AIRTEL = 'MOBILE_MONEY_AIRTEL',
  MOBILE_MONEY_ZAMTEL = 'MOBILE_MONEY_ZAMTEL',
  VISA = 'VISA',
  MASTERCARD = 'MASTERCARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  INSURANCE = 'INSURANCE',
  CASH = 'CASH',
}

export enum ConsentType {
  DATA_PROCESSING = 'DATA_PROCESSING',
  MEDICAL_DATA_SHARING = 'MEDICAL_DATA_SHARING',
  LOCATION_TRACKING = 'LOCATION_TRACKING',
  MARKETING_COMMUNICATIONS = 'MARKETING_COMMUNICATIONS',
  THIRD_PARTY_SHARING = 'THIRD_PARTY_SHARING',
  INSURANCE_DATA_SHARING = 'INSURANCE_DATA_SHARING',
  RESEARCH_PARTICIPATION = 'RESEARCH_PARTICIPATION',
  TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  TELEHEALTH_RECORDING = 'TELEHEALTH_RECORDING',
}

export enum DocumentType {
  HPCZ_CERTIFICATE = 'HPCZ_CERTIFICATE',
  ZAMRA_LICENSE = 'ZAMRA_LICENSE',
  NATIONAL_ID = 'NATIONAL_ID',
  PRACTICING_LICENSE = 'PRACTICING_LICENSE',
  DEGREE_CERTIFICATE = 'DEGREE_CERTIFICATE',
  SPECIALIZATION_CERTIFICATE = 'SPECIALIZATION_CERTIFICATE',
  INSURANCE_CERTIFICATE = 'INSURANCE_CERTIFICATE',
  POLICE_CLEARANCE = 'POLICE_CLEARANCE',
  CV_RESUME = 'CV_RESUME',
  OTHER = 'OTHER',
}

export enum NotificationChannel {
  PUSH = 'PUSH',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  IN_APP = 'IN_APP',
  WHATSAPP = 'WHATSAPP',
}

export enum DataRequestType {
  ACCESS = 'ACCESS',
  RECTIFICATION = 'RECTIFICATION',
  ERASURE = 'ERASURE',
  PORTABILITY = 'PORTABILITY',
  RESTRICTION = 'RESTRICTION',
  OBJECTION = 'OBJECTION',
}

export enum MessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  FILE = 'FILE',
  SYSTEM = 'SYSTEM',
}

export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum ReminderType {
  TWENTY_FOUR_HOURS = 'TWENTY_FOUR_HOURS',
  ONE_HOUR = 'ONE_HOUR',
}

// --- Telehealth & Lab enums (Phase 2) ---

export enum TelehealthSessionStatus {
  WAITING = 'WAITING',
  ACTIVE = 'ACTIVE',
  ENDED = 'ENDED',
  CANCELLED = 'CANCELLED',
}

export enum LabOrderStatus {
  ORDERED = 'ORDERED',
  SAMPLE_COLLECTED = 'SAMPLE_COLLECTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum LabOrderPriority {
  ROUTINE = 'ROUTINE',
  URGENT = 'URGENT',
  STAT = 'STAT',
}

export enum ResultInterpretation {
  NORMAL = 'NORMAL',
  ABNORMAL = 'ABNORMAL',
  CRITICAL = 'CRITICAL',
}

// --- Medication enums (Phase 3) ---

export enum MedicationOrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum ReminderFrequency {
  ONCE_DAILY = 'ONCE_DAILY',
  TWICE_DAILY = 'TWICE_DAILY',
  THREE_TIMES_DAILY = 'THREE_TIMES_DAILY',
  FOUR_TIMES_DAILY = 'FOUR_TIMES_DAILY',
  EVERY_OTHER_DAY = 'EVERY_OTHER_DAY',
  WEEKLY = 'WEEKLY',
  CUSTOM = 'CUSTOM',
}

export enum AdherenceStatus {
  PENDING = 'PENDING',
  TAKEN = 'TAKEN',
  SKIPPED = 'SKIPPED',
  MISSED = 'MISSED',
}

export enum MedicationReminderStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

// --- Referrals & Care Coordination enums (Phase 4.1) ---

export enum ReferralStatus {
  SENT = 'SENT',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ReferralUrgency {
  ROUTINE = 'ROUTINE',
  URGENT = 'URGENT',
  EMERGENCY = 'EMERGENCY',
}

export enum CarePlanStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MilestoneStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

// --- Frontend-only enums (not in Prisma, used for UI dropdowns) ---

export enum BloodType {
  A_POSITIVE = 'A_POSITIVE',
  A_NEGATIVE = 'A_NEGATIVE',
  B_POSITIVE = 'B_POSITIVE',
  B_NEGATIVE = 'B_NEGATIVE',
  AB_POSITIVE = 'AB_POSITIVE',
  AB_NEGATIVE = 'AB_NEGATIVE',
  O_POSITIVE = 'O_POSITIVE',
  O_NEGATIVE = 'O_NEGATIVE',
}

export enum InsuranceProvider {
  NHIMA = 'NHIMA',
  ZSIC = 'ZSIC',
  MADISON = 'MADISON',
  PROFESSIONAL_INSURANCE = 'PROFESSIONAL_INSURANCE',
  OTHER = 'OTHER',
}
