export enum UserRole {
  PATIENT = 'PATIENT',
  PRACTITIONER = 'PRACTITIONER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum PractitionerType {
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  CLINICAL_OFFICER = 'CLINICAL_OFFICER',
  PHYSIOTHERAPIST = 'PHYSIOTHERAPIST',
  PHARMACIST = 'PHARMACIST',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  MIDWIFE = 'MIDWIFE',
  DENTIST = 'DENTIST',
  PSYCHOLOGIST = 'PSYCHOLOGIST',
  NUTRITIONIST = 'NUTRITIONIST',
}

export enum BookingStatus {
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  PRACTITIONER_EN_ROUTE = 'PRACTITIONER_EN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  MOBILE_MONEY_MTN = 'MOBILE_MONEY_MTN',
  MOBILE_MONEY_AIRTEL = 'MOBILE_MONEY_AIRTEL',
  CARD = 'CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  INSURANCE = 'INSURANCE',
}

export enum ServiceType {
  HOME_VISIT = 'HOME_VISIT',
  CLINIC_VISIT = 'CLINIC_VISIT',
  VIRTUAL_CONSULTATION = 'VIRTUAL_CONSULTATION',
}

export enum ConsentType {
  DATA_PROCESSING = 'DATA_PROCESSING',
  MEDICAL_RECORDS_SHARING = 'MEDICAL_RECORDS_SHARING',
  LOCATION_TRACKING = 'LOCATION_TRACKING',
  MARKETING_COMMUNICATIONS = 'MARKETING_COMMUNICATIONS',
  TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
}

export enum DocumentType {
  HPCZ_CERTIFICATE = 'HPCZ_CERTIFICATE',
  ZAMRA_LICENSE = 'ZAMRA_LICENSE',
  NATIONAL_ID = 'NATIONAL_ID',
  QUALIFICATION_CERTIFICATE = 'QUALIFICATION_CERTIFICATE',
  INSURANCE_DOCUMENT = 'INSURANCE_DOCUMENT',
  PRACTICE_LICENSE = 'PRACTICE_LICENSE',
}

export enum NotificationChannel {
  PUSH = 'PUSH',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  IN_APP = 'IN_APP',
}

export enum DataRequestType {
  ACCESS = 'ACCESS',
  RECTIFICATION = 'RECTIFICATION',
  ERASURE = 'ERASURE',
  PORTABILITY = 'PORTABILITY',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum BloodType {
  A_POSITIVE = 'A_POSITIVE',
  A_NEGATIVE = 'A_NEGATIVE',
  B_POSITIVE = 'B_POSITIVE',
  B_NEGATIVE = 'B_NEGATIVE',
  AB_POSITIVE = 'AB_POSITIVE',
  AB_NEGATIVE = 'AB_NEGATIVE',
  O_POSITIVE = 'O_POSITIVE',
  O_NEGATIVE = 'O_NEGATIVE',
}

export enum InsuranceProvider {
  NHIMA = 'NHIMA',
  ZSIC = 'ZSIC',
  MADISON = 'MADISON',
  PROFESSIONAL_INSURANCE = 'PROFESSIONAL_INSURANCE',
  OTHER = 'OTHER',
}
